// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Noto_Kufi_Arabic } from 'next/font/google';
import { AuthProvider } from "./context/AuthContext";
import { ToastContainer } from 'react-toastify';
import 'bootstrap/dist/js/bootstrap.bundle.min';


const notoKufi = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  weight: ['400', '700'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ادارة السناتر التعليمية",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoKufi.className}`}>
        <AuthProvider>
          {children}
        </AuthProvider>
        <ToastContainer position="top-left" />
      </body>
    </html>
  );
}
